### PR TITLE
Update faq.fml

### PR DESCRIPTION
**Pull request by gk2go**
Added dp4j as an option for testing private methods, as discussed on https://groups.yahoo.com/neo/groups/junit/conversations/topics/24683

### CODE REVIEW

**Comment by gk2go** [comment]
@dsaff, what's next with this pull request to updated JUnit's FAQ?

**Comment by dsaff** [comment]
Can you reformat so the raw source stays under ~100 columns?  Thanks.

**Comment by kcooney** [comment]
You need to submit a pull request against junit-team/junit

**Comment by gk2go** [comment]
@kcooney, I have submitted the pull request against junit-team/junit.
@dsaff, I've reformated the raw source to stay under ~ 100 columns.

The new pull request should be junit-team/junit#1188, commit 8d9e2051c21ab4f5c50a1b77d9711a72a55f7896.

**Pull request merged**
